name: interspeechmi
channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - aiohttp=3.8.1=py39h3811e60_0
  - aiosignal=1.2.0=pyhd8ed1ab_0
  - alembic=1.7.5=pyhd8ed1ab_0
  - alsa-lib=1.2.3=h516909a_0
  - anyio=3.4.0=py39hf3d152e_0
  - argon2-cffi=21.1.0=py39h3811e60_2
  - arrow-cpp=6.0.1=py39hb8c629c_3_cpu
  - async-timeout=4.0.1=pyhd8ed1ab_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - autopage=0.5.0=pyhd8ed1ab_0
  - aws-c-auth=0.6.8=hfef2836_0
  - aws-c-cal=0.5.12=h70efedd_7
  - aws-c-common=0.6.17=h7f98852_0
  - aws-c-compression=0.2.14=h7c7754b_7
  - aws-c-event-stream=0.2.7=hb80ed28_31
  - aws-c-http=0.6.10=h58a30cf_2
  - aws-c-io=0.10.13=he836878_5
  - aws-c-mqtt=0.7.9=h042a236_0
  - aws-c-s3=0.1.27=h4f4cd48_12
  - aws-c-sdkutils=0.1.1=h7c7754b_4
  - aws-checksums=0.1.12=h7c7754b_6
  - aws-crt-cpp=0.17.9=hc7d31a4_1
  - aws-sdk-cpp=1.9.154=h77f1c7e_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=h7f98852_6
  - brotli-bin=1.0.9=h7f98852_6
  - brotlipy=0.7.0=py39h3811e60_1003
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2021.10.8=ha878542_0
  - catalogue=2.0.6=py39hf3d152e_0
  - certifi=2021.10.8=py39hf3d152e_1
  - cffi=1.15.0=py39h4bc2ebd_0
  - charset-normalizer=2.0.8=pyhd8ed1ab_0
  - click=8.0.3=py39hf3d152e_1
  - cliff=3.10.0=pyhd8ed1ab_0
  - cmaes=0.8.2=pyh44b312d_0
  - cmd2=2.3.3=py39hf3d152e_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - colorlog=6.6.0=py39hf3d152e_0
  - cryptography=36.0.0=py39h95dcef6_0
  - cudatoolkit=11.1.1=h6406543_9
  - cudnn=8.2.1.32=h86fa8c9_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - cymem=2.0.6=py39he80948d_2
  - cython-blis=0.7.5=py39hce5d2b2_1
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=1.18.2=py_0
  - dbus=1.13.6=h48d8840_2
  - debugpy=1.5.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dill=0.3.4=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - expat=2.4.1=h9c3ff4c_0
  - filelock=3.4.0=pyhd8ed1ab_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.28.2=py39h3811e60_0
  - freetype=2.10.4=h0708190_1
  - frozenlist=1.2.0=py39h3811e60_1
  - fsspec=2021.11.1=pyhd8ed1ab_0
  - ftfy=5.8=py_0
  - future=0.18.2=py39hf3d152e_4
  - gensim=4.1.2=py39he80948d_0
  - gettext=0.19.8.1=h73d1719_1008
  - gflags=2.2.2=he1b5a44_1004
  - glib=2.70.1=h780b84a_0
  - glib-tools=2.70.1=h780b84a_0
  - glog=0.5.0=h48cff8f_0
  - greenlet=1.1.2=py39he80948d_1
  - grpc-cpp=1.42.0=h7e358d9_0
  - gst-plugins-base=1.18.5=hf529b03_2
  - gstreamer=1.18.5=h9f60fe5_2
  - huggingface_hub=0.2.0=pyhd8ed1ab_0
  - icu=68.2=h9c3ff4c_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.2=py39hf3d152e_0
  - importlib_metadata=4.8.2=hd8ed1ab_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - ipykernel=6.5.1=py39hef51801_0
  - ipython=7.30.1=py39hf3d152e_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h7f98852_2003
  - jedi=0.18.1=py39hf3d152e_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.2.1=pyhd8ed1ab_0
  - jupyter_client=7.1.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hf3d152e_1
  - jupyter_server=1.12.1=pyhd8ed1ab_0
  - jupyterlab=3.2.4=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - kiwisolver=1.3.2=py39h1a9c180_1
  - krb5=1.19.2=hcc1bbae_3
  - langcodes=3.3.0=pyhd8ed1ab_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libbrotlicommon=1.0.9=h7f98852_6
  - libbrotlidec=1.0.9=h7f98852_6
  - libbrotlienc=1.0.9=h7f98852_6
  - libcblas=3.9.0=12_linux64_mkl
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.80.0=h2574ce0_0
  - libdeflate=1.8=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.70.1=h174f98d_0
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=12_linux64_mkl
  - libllvm11=11.1.0=hf817b99_2
  - libnghttp2=1.43.0=h812cca2_1
  - libogg=1.3.4=h7f98852_1
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.37=h21135ba_2
  - libpq=13.5=hd57d9b9_0
  - libprotobuf=3.18.1=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libssh2=1.10.0=ha56f1ee_2
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libthrift=0.15.0=he6d91bd_1
  - libtiff=4.3.0=h6f004c6_2
  - libutf8proc=2.6.1=h7f98852_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.42.0=h7f98852_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.2.1=h7f98852_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.11=h36c2ea0_1013
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - magma=2.5.4=ha9b7cf9_2
  - mako=1.1.6=pyhd8ed1ab_0
  - markupsafe=2.0.1=py39h3811e60_1
  - matplotlib=3.5.0=py39hf3d152e_0
  - matplotlib-base=3.5.0=py39h2fa2bec_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39h3811e60_1005
  - mkl=2021.4.0=h8d4b97c_729
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - msgpack-python=1.0.3=py39h1a9c180_0
  - multidict=5.2.0=py39h3811e60_1
  - multiprocess=0.70.12.2=py39h3811e60_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - murmurhash=1.0.6=py39he80948d_2
  - mysql-common=8.0.27=ha770c72_1
  - mysql-libs=8.0.27=hfa10184_1
  - nbclassic=0.3.4=pyhd8ed1ab_0
  - nbclient=0.5.9=pyhd8ed1ab_0
  - nbconvert=6.3.0=py39hf3d152e_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nccl=2.11.4.1=h97a9cb7_0
  - ncurses=6.2=h58526e2_4
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - networkx=2.6.3=pyhd8ed1ab_1
  - ninja=1.10.2=h4bd325d_1
  - nltk=3.6.5=pyhd8ed1ab_0
  - notebook=6.4.6=pyha770c72_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.73=hb5efdd6_0
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.21.2=py39h20f2e39_0
  - numpy-base=1.21.2=py39h79a1101_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb52868f_1
  - openssl=1.1.1l=h7f98852_0
  - optuna=2.10.0=pyhd8ed1ab_0
  - orc=1.7.1=h68e2c4e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.3.4=py39h8c16a72_0
  - pandoc=2.16.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parquet-cpp=1.5.1=2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathy=0.6.1=pyhd8ed1ab_0
  - pbr=5.8.0=pyhd8ed1ab_1
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py39ha612740_0
  - pip=21.3.1=pyhd8ed1ab_0
  - preshed=3.0.6=py39he80948d_1
  - prettytable=3.0.0=pyhd8ed1ab_0
  - prometheus_client=0.12.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.22=pyha770c72_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyarrow=6.0.1=py39hff6fa39_3_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=1.8.2=py39h3811e60_2
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.6=pyhd8ed1ab_0
  - pyperclip=1.8.2=pyhd8ed1ab_2
  - pyqt=5.12.3=py39hf3d152e_8
  - pyqt-impl=5.12.3=py39hde8b62d_8
  - pyqt5-sip=4.19.18=py39he80948d_8
  - pyqtchart=5.12=py39h0fcd23e_8
  - pyqtwebengine=5.12.1=py39h0fcd23e_8
  - pyrsistent=0.18.0=py39h3811e60_0
  - pysocks=1.7.1=py39hf3d152e_4
  - python=3.9.7=hb7a2778_3_cpython
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py39h3811e60_1
  - python_abi=3.9=2_cp39
  - pytorch=1.10.0=cuda111py39hb4a4491_0
  - pytorch-gpu=1.10.0=cuda111py39h788eb59_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyyaml=6.0=py39h3811e60_3
  - pyzmq=22.3.0=py39h37b5a0c_1
  - qt=5.12.9=hda022c4_4
  - re2=2021.11.01=h9c3ff4c_0
  - readline=8.1=h46c0cb4_0
  - regex=2021.11.10=py39h3811e60_0
  - requests=2.26.0=pyhd8ed1ab_1
  - s2n=1.3.0=h9b69904_0
  - sacremoses=0.0.46=pyhd8ed1ab_0
  - scikit-learn=1.0.1=py39h4dfa638_2
  - scipy=1.7.1=py39h292c36d_2
  - seaborn=0.11.2=pyhd3eb1b0_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - sentence-transformers=2.1.0=pyhd8ed1ab_0
  - sentencepiece=0.1.95=py39h1a9c180_1
  - setuptools=59.4.0=py39hf3d152e_0
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - smart_open=5.2.1=pyhd8ed1ab_0
  - snappy=1.1.8=he1b5a44_3
  - sniffio=1.2.0=py39hf3d152e_2
  - spacy=3.2.0=py39h5472131_0
  - spacy-legacy=3.0.8=pyhd8ed1ab_0
  - spacy-loggers=1.0.1=pyhd8ed1ab_0
  - spacy-model-en_core_web_lg=3.2.0=pyhd8ed1ab_0
  - spacy-model-en_core_web_sm=3.2.0=pyhd8ed1ab_0
  - sqlalchemy=1.4.31=py39h3811e60_0
  - sqlite=3.37.0=h9cd32fc_0
  - srsly=2.4.2=py39he80948d_0
  - stevedore=3.5.0=py39hf3d152e_2
  - tbb=2021.4.0=h4bd325d_1
  - terminado=0.12.1=py39hf3d152e_1
  - testpath=0.5.0=pyhd8ed1ab_0
  - thinc=8.0.12=py39h5472131_0
  - threadpoolctl=3.0.0=pyh8a188c0_0
  - tk=8.6.11=h27826a3_1
  - tokenizers=0.10.3=py39hd6d55de_1
  - torchvision=0.10.1=py39cuda111hcd06603_0_cuda
  - tornado=6.1=py39h3811e60_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - transformers=4.15.0=pyhd8ed1ab_0
  - typer=0.4.0=pyhd8ed1ab_0
  - typing-extensions=4.0.1=hd8ed1ab_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - unidecode=1.3.3=pyhd8ed1ab_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - wasabi=0.8.2=pyh44b312d_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=1.2.1=py39hf3d152e_0
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.2=py39hf3d152e_1
  - wordfreq=2.5.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xxhash=0.8.0=h7f98852_3
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h516909a_0
  - yarl=1.7.2=py39h3811e60_1
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h36c2ea0_1013
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - bert-score==0.3.10
    - build==0.7.0
    - pep517==0.12.0
    - tomli==1.2.2
prefix: /home/mustafa/anaconda3/envs/interspeechmi
